version: "3.3"
services:
  openbooks:
    container_name: OpenBooks
    restart: unless-stopped
    image: evanbuss/openbooks
    volumes:
      - ~/Downloads/books/:/books
    ports:
      - "8080:80"
    command: --persist --name pizero -s irc.irchighway.net:6697 
    environment:
      - BASE_PATH=/
