- name: Install load balancer
  become: true
  when: "'load_balancer' in group_names"
  block:
    - name: Install haproxy
      ansible.builtin.apt:
        name: [haproxy]
    - name: Generate haproxy configu
      ansible.builtin.template:
        src: templates/haproxy.conf.j2
        dest: /etc/haproxy/haproxy.conf
        owner: root
        group: root
        mode: "0644"

    - name: Enable and restart HAProxy
      ansible.builtin.systemd:
        name: haproxy
        state: restarted
        enabled: true
