apiVersion: v1
kind: Service
metadata:
  labels:
    app: audiobookshelf
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  ports:
    - name: audiobookshelf
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30081
  selector:
    app: audiobookshelf
  type: NodePort
