# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  labels:
    app: filebrowser
spec:
  selector:
    matchLabels:
      app: qbittorrent
  replicas: 1
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          ports:
            - containerPort: 80
              name: myjob
          volumeMounts:
            - name: media
              mountPath: /downloads
            - name: qbittorrent-config
              mountPath: /config
      volumes:
        - name: media
          nfs:
            server: 192.168.1.67
            path: /media
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
      restartPolicy: Always
---

