services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.audiobookshelf.rule=Host(`audiobooks.manujkarki.com.np`)"
      - "traefik.http.routers.audiobookshelf.entrypoints=websecure"
      - "traefik.http.routers.audiobookshelf.tls=true"
      - "traefik.http.routers.audiobookshelf.tls.certresolver=letencrypt"
      - "traefik.http.routers.audiobookshelf.middlewares=authelia"
    ports:
      - 13378:80
    volumes:
      - /home/omen/Audiobooks/:/audiobooks
      - /home/omen/Podcasts:/podcasts
      - ./config:/config
      - ./metadata:/metadata
    environment:
      - TZ=Nepal/Kathmandu
