apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  labels:
    app: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
    spec:
      containers:
        - image: ghcr.io/paperless-ngx/paperless-ngx:latest
          name: paperless
          env:
            - name: PAPERLESS_TIME_ZONE
              value: "Asia/Kathmandu"
            - name: COMPOSE_PROJECT_NAME
              value: paperless
            - name: PAPERLESS_PORT
              value: "8000"
            - name: PAPERLESS_REDIS
              value: "redis://paperless-redis:6379"
            - name: PAPERLESS_DBHOST
              value: "paperless-postgres"
            - name: PAPERLESS_URL
              value: https://paperless.manujkarki.com.np
            - name: PAPERLESS_CONSUMER_POLLING
              value: "10"
            - name: PAPERLESS_OCR_LANGUAGES
              value: nep
            - name: PAPERLESS_FILENAME_FORMAT
              value: "{{ original_name }}"
          volumeMounts:
            - mountPath: /usr/src/paperless/data
              name: paperless-data
            - mountPath: /usr/src/paperless/media
              subPath: paperless/media
              name: paperless-nfs
            - mountPath: /usr/src/paperless/export
              subPath: paperless/export
              name: paperless-nfs
            - mountPath: /usr/src/paperless/consume
              subPath: paperless/consume
              name: paperless-nfs
      volumes:
        - name: paperless-data
          persistentVolumeClaim:
            claimName: paperless-data
        - name: paperless-nfs
          nfs:
            server: 192.168.1.67
            path: /media/apps

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-redis
  labels:
    app: paperless-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless-redis
  template:
    metadata:
      labels:
        app: paperless-redis
    spec:
      containers:
        - image: docker.io/library/redis:7
          name: paperless-redis
          ports:
            - containerPort: 6379
              name: paperless-redis
          volumeMounts:
            - mountPath: /data
              name: paperless-redis
      volumes:
        - name: paperless-redis
          persistentVolumeClaim:
            claimName: paperless-redis

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: paperless-postgres
  labels:
    app: paperless-postgres
spec:
  serviceName: paperless-postgres
  replicas: 1
  selector:
    matchLabels:
      app: paperless-postgres
  template:
    metadata:
      labels:
        app: paperless-postgres
    spec:
      containers:
        - image: postgres:17.5
          name: paperless-postgres
          ports:
            - containerPort: 5432
              name: paperless-pg
          env:
            - name: POSTGRES_DB
              value: paperless
            - name: POSTGRES_USER
              value: paperless
            - name: POSTGRES_PASSWORD
              value: paperless
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: paperless-postgres
              readOnly: false
      volumes:
        - name: paperless-postgres
          persistentVolumeClaim:
            claimName: paperless-postgres
