apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless
spec:
  rules:
    - host: paperless.manujkarki.com.np
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paperless
                port:
                  number: 8000
