apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-certificate-secret
  namespace: monitoring
spec:
  secretName: grafana-certificate-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - grafana.manujkarki.com.np
