- name: Main
  hosts: all
  pre_tasks:
    - name: Update apt
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
        - tailscale
        - docker
        - nginx
        - ssl
  roles:
    - core
    - docker
    - tailscale
    # - ssh
    - ufw
    - { role: "nginx", tags: ["nginx"] }
    # - { role: "ssl", tags: ["ssl"] }
