version: "3"
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - /mnt/media:/srv #Change to match your directory
      - ./filebrowser.db:/database.db #Change to match your directory
    user: "1000:100"
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
    ports:
      - 9080:80 #Change the port if needed
    networks:
      - homelab
networks:
  homelab:
    external: true
