services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`file.manujkarki.com.np`)"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.routers.filebrowser.tls.certresolver=letencrypt"
      - "traefik.http.routers.filebrowser.middlewares=authelia"
      # - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
    restart: unless-stopped
    volumes:
      - /mnt/media:/srv #Change to match your directory
      - ./filebrowser.db:/database.db #Change to match your directory
    user: "1000:100"
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
    ports:
      - 9080:80 #Change the port if needed
    networks:
      - homelab
networks:
  homelab:
    external: true
